apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::646418206500:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-kuVzDYB53MdS
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::646418206500:user/suresh
      username: suresh
metadata:
  creationTimestamp: "2026-04-22T06:27:38Z"
  name: aws-auth
  namespace: kube-system
  uid: 6381417a-909c-4536-9966-b3b7ceb75c34

